version: '3'

services:
  database:
    image: mysql:5.7
    ports: 
      - '3306:3306'
    environment:
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: description
    volumes:
      - ./dataDump:/docker-entrypoint-initdb.d
  
  description:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3002:3002'